tasks:
  - name: conda
    init: |
      wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.11.0-Linux-x86_64.sh -O $HOME/miniconda.sh
      chmod +x $HOME/miniconda.sh
      $HOME/miniconda.sh -b -p $HOME/miniconda
      $HOME/miniconda/condabin/conda init bash
      source $HOME/.bashrc
      conda env create -f brightway/environment.yml
    command: conda activate env
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
