tasks:
  - name: conda
    init: |
      # install miniconda
      wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.11.0-Linux-x86_64.sh -O /tmp/miniconda.sh
      chmod +x /tmp/miniconda.sh
      /tmp/miniconda.sh -b -p /workspace/miniconda
      /workspace/miniconda/condabin/conda init bash

      # setup the PATH to include miniconda's bin folder
      gp env PATH=/workspace/miniconda/bin:/workspace/miniconda/condabin:$PATH
      # update the current terminal session with the latest set of persistent environment variables
      eval $(gp env -e)

      # create the virtual environment and install the dependencies
      conda env create -f brightway/environment.yml
    before: conda init bash
    command: conda activate env

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
