tasks:
  - name: conda
    env:
      PATH: /workspace/miniconda/bin:/workspace/miniconda/condabin:$PATH
    init: |
      ./install_miniconda.sh
      conda env create -f brightway/environment.yml
    command: conda activate env
vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
