ACCOUNT_LOGIN = "/api/access/login"
ACCOUNT_LOGOUT = "/api/access/logout"
ACCOUNT_REGISTER_MAGIC_LINK = "/api/access/magic_link/signup"
ACCOUNT_LOGIN_MAGIC_LINK = "/api/access/magic_link/login"
ACCOUNT_PROFILE = "/api/me"
USER_DETAIL = "/api/users/{user_id:uuid}"
