name: Data pipeline

env:
  ECOBALYSE_DATA_DIR: ./ecobalyse-private
  DB_FILES_DIR: ./ecobalyse-private/dbfiles
  PYTHONPATH: .
on:
  push:
    branches: [ main ]

  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        python-version: [3.11]

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 10000
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('package.json', 'package-lock.json') }}

      - name: Install Node dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}

      - name: Clone the private repo
        run: |
          eval `ssh-agent -s`
          # Private ssh key used by this Github action to clone the private repo
          # The corresponding public key must be set as a deploy key of the private repo
          ssh-add - <<< '${{ secrets.PRIVATE_SSH_KEY }}'
          git clone git@github.com:MTES-MCT/ecobalyse-private.git
          cd ecobalyse-private
          git checkout chore/use-git-lfs-for-dbs

      - name: Import all
        run: |
          npm run import:all

      - name: Export all
        run: |
          npm run export:all
